#!/bin/bash
source devel/setup.bash
rosservice call shutdown
rosservice call /gazebo/set_model_state '{model_state: { model_name: quadrotor, pose: { position: { x: 0, y: 0 ,z: 0 }, orientation: {x: 0, y: 0, z: 0, w: 0} }, twist: { linear: {x: 0.0 , y: 0 ,z: 0 } , angular: { x: 0.0 , y: 0 , z: 0.0 } } , reference_frame: world } }'

